import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const source = readFileSync(new URL('../extensions/hybrid-memory.ts', import.meta.url), 'utf8');
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

assert.match(source, /sk-\(\?:ant-\|proj-\)\?\[A-Za-z0-9_-\]\{16,\}/, 'redaction should cover plain sk-... plus sk-ant-/sk-proj- keys');
assert.doesNotMatch(source.match(/function durablePreferencePrompt[\s\S]*?\n}/)?.[0] ?? '', /\bi want\b/i, 'session preference import should not treat broad "i want" as durable');
assert.match(source, /function hybridMemoryConfig/, 'tuning knobs should load from OMP settings');
assert.match(source, /withFileMutationQueue/, 'mutating memory tools should use the local file mutation queue for parallel tool safety');
assert.match(source, /function withHybridMemoryMutation/, 'mutating memory tools should share a local memory mutation wrapper');
assert.match(source, /withFileMutationQueue\(join\(p\.user, RECORDS\)/, 'memory mutation queue should serialize user records first');
assert.match(source, /withFileMutationQueue\(join\(p\.project, RECORDS\)/, 'memory mutation queue should serialize project records too');
assert.match(source, /const max = boundedNumber\(args\.trim\(\), hybridMemoryConfig\(ctx\.cwd\)\.pruneActiveSessionRecaps, 3, 100\);/, '/hmemory-prune should use boundedNumber with the configured default for invalid input');
assert.match(source, /\["ls-files", "--others", "--exclude-standard"\]/, 'repo map should include untracked non-ignored git files');
assert.match(source, /added after repo map generation/, 'repo map staleness should detect newly added files');
assert.match(source, /slice\(0, config\.repoMapFileLimit\)/, 'repo-map file cap should be configurable');
assert.match(source, /size <= config\.repoMapReadMaxBytes/, 'repo-map read-size cap should be configurable');
assert.match(source, /!path\.startsWith\("\.omp\/"\)/, 'repo map should avoid indexing project .omp memory state');
assert.match(source, /REPO_NOISE_TOP_LEVEL/, 'repo map should define a noise filter for home-directory caches');
assert.match(source, /isNoisyRepoPath\(path\)/, 'repo map should skip noisy home/cache paths before injection');
assert.match(source, /function isHomeRepoNoise/, 'repo map should apply extra root-aware filtering when cwd is the home directory');
assert.match(source, /HOME_REPO_NOISE_TOP_LEVEL/, 'home repo maps should not index Dev, node_modules, backups, or personal folders');
assert.match(source, /id_rsa\|id_dsa\|id_ecdsa\|id_ed25519\|adbkey/, 'sensitive path filter should cover Android adb keys');
assert.match(source, /\.npmrc\|\\\.netrc\|\\\.emulator_console_auth_token/, 'sensitive path filter should cover common home credential files');
assert.match(source, /function autoCapturePromptMemory/, 'durable preference prompts should be auto-captured before the agent starts');
assert.match(source, /function looksLikePastedReviewPrompt/, 'pasted reviews should not be auto-captured as preferences');
assert.match(source, /function looksLikeContextInspectionText/, 'sessions that quote injected context should be treated as diagnostic noise');
assert.match(source, /looksLikeContextInspectionText\(text\)/, 'context-inspection prompts should be excluded before session recap import');
assert.match(source, /context-inspection-recap/, 'context-inspection recaps should be prunable stale');
assert.match(source, /function isUsefulProjectCommand/, 'session command recipes should skip generic inspection commands');
assert.match(source, /function staleCodebaseNoteReason/, 'codebase notes should become stale when referenced source files change');
assert.match(source, /staleCodebaseNotesOnFileChange: true/, 'codebase-note staleness should be enabled by default');
assert.match(source, /function isActiveRecord/, 'memory visibility should share one active-status predicate');
assert.match(source, /isActiveRecord\(x\.record\) && x\.score > 0 && shouldIncludeSearchHit\(cwd, x\.record, query\)/, 'pinned records should still need scoped relevance before search/injection');
assert.match(source, /function readFirstJsonlObject/, 'project session filtering should read only the first JSONL object');
assert.doesNotMatch(source, /readJsonlObjects\(file\)\[0\]/, 'project session filtering should not parse whole session files');
assert.match(source, /function normalizeMemoryRecord/, 'manual JSONL records should be normalized before stats/search use them');
assert.match(source, /function recordMeaningfulSnapshot/, 'stable imports should append a new head when meaningful metadata changes');
assert.match(source, /SESSION_IMPORT_MAX_BYTES/, 'current-session auto-import should share the bounded session size guard');
assert.match(source, /repoMapStalenessCached\(ctx\.cwd\)/, 'status chrome should use cached repo-map staleness');
assert.match(source, /const active = `\$\{ctx\.ui\.theme\.fg\("success", String\(counts\.active\)\)\} \$\{ctx\.ui\.theme\.fg\("dim", "active"\)\}`;/, 'status chrome should spell out active count instead of cryptic abbreviations');
assert.match(source, /const scopes = \[user, project\]\.filter\(Boolean\)\.join\(" • "\);/, 'status chrome should omit zero-count scope segments cleanly');
assert.match(source, /\$\{active\}\$\{scopes \? ` • \$\{scopes\}` : ""\}\$\{pinned\} • \$\{repo\}/, 'status chrome should include labeled active/scope/pinned/repo health segments');
assert.doesNotMatch(source, /\$\{counts\.active\}a\/\$\{counts\.project\}p/, 'status chrome should not use unexplained a/p abbreviations');
assert.match(source, /pi\.on\("agent_end"/, 'current session should be re-imported after each agent turn');
assert.match(source, /stableId\("preference", content, `auto-prompt:\$\{content\}`\)/, 'auto-captured and session-imported preferences should dedupe by content');
assert.match(source, /const MAX_INJECT_CHARS = 4200;/, 'memory injection should stay lean by default');
assert.match(source, /config\.maxInjectChars/, 'memory injection cap should be configurable');
assert.match(source, /config\.injectSectionLimits\[title\]/, 'per-section injection limits should be configurable');
assert.match(source, /function displaySessionRecap/, 'session recaps should be rendered as clean outcomes and topics');
assert.match(source, /function dedupeInjectionRecords/, 'injected memory should dedupe noisy near-identical records');
assert.match(source, /function shouldInjectSessionRecap/, 'session recap injection should hide diagnostic context-inspection recaps');
assert.match(source, /function sessionRecapCommitKeys/, 'session recap injection should collapse repeated commit recaps');
assert.match(source, /function isLowSignalSessionFilePath/, 'session recap file displays should hide low-signal screenshot/media paths');
assert.match(source, /function isPackageDocsPath/, 'session recap file displays should identify package/docs paths as low-priority');
assert.match(source, /function injectedRecordFilePaths/, 'injected file suffixes should prefer project-local session recap paths');
assert.match(source, /const projectLocal = paths\.filter\(\(p\) => isProjectDisplayPath\(cwd, p\)\);/, 'session recap injection should prefer project-local file paths');
assert.match(source, /const withoutPackageDocs = paths\.filter\(\(p\) => !isPackageDocsPath\(p\)\);/, 'session recap injection should hide package/docs paths when better paths exist');
assert.match(source, /function distinctiveQueryTerms/, 'global user technical memories should require distinctive prompt matches');
assert.match(source, /const RECIPE_DISPLAY_COMMAND_LIMIT = 6;/, 'recipe injection should show six short validation commands before +N more');
assert.match(source, /function shouldInjectPinnedByDefault/, 'pinned global records should still be scoped before default injection');
assert.match(source, /function commandFamilyKey/, 'recipe commands should dedupe by command family');
assert.match(source, /function visibleWidth/, 'TUI padding should use terminal cell widths for Unicode icons');
assert.match(source, /import \{[^}]*Text[^}]*\} from "@oh-my-pi\/pi-tui";/, 'custom tool renderers should use the official Pi TUI Text component');
assert.equal(packageJson.peerDependencies?.['@oh-my-pi/pi-tui'], '*', 'package should declare OMP pi-tui as a peer dependency for custom renderers');
assert.match(source, /function memoryKindIcon/, 'memory review and tool renderers should share kind icons');
assert.match(source, /case "preference": return "💜";/, 'preference memories should keep a friendly icon');
assert.match(source, /const labelText = padVisible\(reviewKindLabel\(r\), 18\)/, 'memory review kind labels should use a fixed-width Unicode-safe column');
assert.match(source, /const pin = padVisible\(r\.pinned \? warp\.pink\("📌"\) : "", 2\)/, 'memory review pinned marker should keep the friendly pinned emoji in a fixed-width slot');
assert.match(source, /const REVIEW_LIST_ROWS = 11;/, 'memory review should use a fixed-size list viewport');
assert.match(source, /for \(let i = 0; i < REVIEW_LIST_ROWS; i\+\+\)/, 'memory review should pad list rows to keep overlay height stable');
assert.match(source, /pi\.registerCommand\("hmemory-doctor"/, 'memory doctor command should be registered for deterministic curation');
assert.match(source, /function memoryStatsSnapshot/, 'memory stats should distinguish active/inactive counts by scope/status/kind');
assert.match(source, /function searchRecordsWithOptions/, 'memory search should support filtered active/all scope/kind/status queries');
assert.match(source, /function scoreRecordWithSearchOptions/, 'status-specific inactive searches should not be hidden by normal stale/superseded scoring penalties');
assert.match(source, /function strongQueryTerms/, 'exact package/path-like memory searches should filter unrelated generic matches');
assert.match(source, /Use one hybrid_memory_search call for both user and project memory by default/, 'memory search tool guidance should discourage duplicate identical scope checks');
assert.match(source, /name: "hybrid_memory_doctor"/, 'memory doctor should be available as a tool for agents');
assert.match(source, /writeMemoryDoctorReport/, 'memory doctor should write a reviewable before/after report');
assert.match(source, /status: Type\.Optional\(StringEnum\(searchStatusEnum\)\)/, 'hybrid_memory_search should expose status filters');
assert.match(source, /includeInactive: Type\.Optional\(Type\.Boolean\(\)\)/, 'hybrid_memory_search should expose an includeInactive/all-history option');
assert.match(source, /function formatForgetPreview/, '/hmemory-forget should preview matching records when given query text instead of an id');
assert.match(source, /tombstone: Type\.Optional\(Type\.Boolean\(\)\)/, 'hybrid_memory_forget should support tiny do-not-suggest tombstones for removed items');
assert.match(source, /tombstoneNote: Type\.Optional\(Type\.String\(\)\)/, 'hybrid_memory_forget should expose tombstoneNote for concise negative preferences');
assert.match(source, /pi\.registerCommand\("hmemory-audit"/, 'memory audit command should be registered');
assert.match(source, /complete\(\n    ctx\.model,\n    \{ systemPrompt: MEMORY_AUDIT_SYSTEM_PROMPT, messages: \[message\] \}/, 'memory audit should use the selected OMP model through pi-ai complete');
assert.match(source, /function applyMemoryAuditPlan/, 'memory audit should be able to apply validated structured cleanup actions');
assert.match(source, /type\": \"merge_records\"/, 'memory audit prompt should support model-proposed dedupe merges');
assert.match(source, /lastAuditAppliedAt/, 'memory audit should persist apply metadata in project state');
assert.match(source, /function createMemoryAuditProgress/, 'memory audit should show a staged progress UI while the model call runs');
assert.match(source, /CancellableLoader/, 'memory audit progress UI should remain cancellable');
assert.match(source, /const visualAudit = await ctx\.ui\.custom<MemoryAuditResult \| null>/, 'memory audit should distinguish visual UI result from non-visual fallback');
assert.match(source, /if \(visualAudit === null\) return ctx\.ui\.notify\("memory audit cancelled", "info"\);/, 'memory audit should treat null as explicit user cancel');
assert.match(source, /if \(!audit\) \{\n          audit = await generateMemoryAudit/, 'memory audit should fall back when custom UI is unavailable in non-TUI modes');
assert.doesNotMatch(source.match(/async function generateMemoryAudit[\s\S]*?\n}/)?.[0] ?? '', /temperature:/, 'memory audit should not pass temperature because Codex models reject it');
assert.match(source, /function asInactiveStatus/, 'memory audit set_status and merge source statuses should stay inactive-only');
assert.match(source, /const fileText = files\.length \? files\.join\("  "\) : warp\.dim\("—"\);/, 'memory review should reserve the files row to keep overlay height stable');
assert.match(source, /theme\.bg\(selected \? "selectedBg" : "customMessageBg", text\)/, 'memory review overlay rows should use a theme background so underlying transcript does not show through');
assert.match(source, /if \(code\.startsWith\("38;"\)\) return `\\x1b\[\$\{code\}m\$\{text\}\\x1b\[39m`;/, 'review overlay foreground colors should not clear row backgrounds with full SGR resets');
assert.match(source, /for \(let i = 0; i < REVIEW_DETAIL_ROWS; i\+\+\) lines\.push\(row\(detailRows\[i\] \?\? ""\)\);/, 'memory review should render a fixed-size details footer');
assert.match(source, /function memoryToolCall/, 'hybrid memory tools should share polished call rendering helpers');
assert.match(source, /return new Text\(text, 0, 0\);/, 'hybrid memory tool renderers should return Text components');
assert.match(source, /renderCall\(args, _options, theme\)/, 'hybrid memory tools should provide custom call rendering');
assert.match(source, /renderResult\(result, \{ expanded, isPartial \}, theme\)/, 'hybrid memory tools should provide custom result rendering with expanded and partial states');
assert.equal((source.match(/name: "hybrid_memory_/g) ?? []).length, (source.match(/renderCall\(args, _options, theme\)/g) ?? []).length, 'every hybrid memory tool should render a custom call row');
assert.equal((source.match(/name: "hybrid_memory_/g) ?? []).length, (source.match(/renderResult\(result, \{ expanded, isPartial \}, theme\)/g) ?? []).length, 'every hybrid memory tool should render a custom result row');
assert.doesNotMatch(source, /reviewKindLabel\(r\)\.padEnd/, 'memory review should not pad icon labels by raw string length');
assert.match(source, /"Relevant Session Recaps": 2/, 'session recap injection should be tightly capped by default');
assert.match(source, /Prior session \(\$\{location\}\)/, 'session recaps should use compact location labels instead of raw cwd prefixes');
assert.match(source, /DEFAULT_AUTO_PRUNE_ACTIVE_SESSION_RECAPS = 8/, 'turn/startup refresh should prune old session recap noise by default');
assert.match(source, /pruneMemory\(cwd, hybridMemoryConfig\(cwd\)\.autoPruneActiveSessionRecaps\)/, 'turn refresh should use the configured auto-prune recap cap');
assert.match(source, /pruneMemory\(cwd, config\.autoPruneActiveSessionRecaps\)/, 'startup refresh should use the configured auto-prune recap cap');
assert.doesNotMatch(source, /function extractSymbols\(/, 'unused extractSymbols wrapper should stay removed');
assert.match(source, /finally \{\n        updateMemoryChrome\(ctx\);\n      \}/, 'long-running commands should restore the memory chrome after temporary statuses');
assert.doesNotMatch(source, /registerCommand\("hmemory-widget"/, 'persistent hmemory widget command should stay removed');
assert.match(source, /clearRemovedWidget\(ctx\);/, 'extension startup/reload should clear any old persistent hybrid-memory widget');

console.log('omp-hybrid-memory tests ok');
