import { readFileSync } from "node:fs";
import { join } from "node:path";

import { atomicWriteFileSync } from "../core/atomic-file.ts";
import { scopeEnum, type MemoryRecord, type MemoryScope } from "../core/domain.ts";
import { purgeScopedRecordVersions } from "../core/jsonl-maintenance.ts";
import { cleanArgToken } from "../core/text.ts";
import { AUDITS, RECORDS, ensureDir, initializeDir, invalidateRecordsCache, nowIso, parseScopedId, paths, projectMemoryDir, regenerateSummary, resolveRecord, updateProjectState } from "./foundation.ts";
import { regenerateProjectContext } from "./repo-context.ts";

export type PurgeMemoryResult = { id: string; scope?: MemoryScope; removed: number; auditPath?: string; ambiguous?: MemoryRecord[] };

export function parseMemoryPurgeArgs(args: string) {
  const tokens = args.match(/(?:"[^"]*"|'[^']*'|\S+)/g)?.map(cleanArgToken) ?? [];
  let force = false;
  let scope: MemoryScope | undefined;
  const id: string[] = [];
  for (let index = 0; index < tokens.length; index++) {
    const token = tokens[index]!;
    if (/^(?:--?force|force)$/i.test(token)) force = true;
    else if (token.startsWith("--scope")) {
      const value = token.includes("=") ? token.split("=")[1] : tokens[++index];
      if (scopeEnum.includes(value as MemoryScope)) scope = value as MemoryScope;
    } else {
      id.push(token);
    }
  }
  return { id: id.join(" ").trim(), scope, force };
}

function writeMemoryPurgeAudit(cwd: string, result: PurgeMemoryResult) {
  const dir = join(projectMemoryDir(cwd), AUDITS);
  ensureDir(dir);
  const file = join(dir, `${nowIso().replace(/[:.]/g, "-")}-hmemory-purge.md`);
  atomicWriteFileSync(file, [
    "<!-- Generated by pi-hybrid-memory /hmemory-purge. Purged content is intentionally not logged. -->",
    `Generated: ${nowIso()}`,
    `Purged: ${result.scope}:${result.id}`,
    `Removed JSONL entries: ${result.removed}`,
    "",
    "No purged record content was written to this audit marker.",
  ].join("\n") + "\n");
  return file;
}

export function purgeMemoryRecord(cwd: string, rawId: string, scope?: MemoryScope): PurgeMemoryResult {
  const parsed = parseScopedId(rawId);
  const wantedScope = scope ?? parsed.scope;
  const resolved = resolveRecord(cwd, parsed.id, wantedScope);
  if (resolved.ambiguous?.length) return { id: parsed.id, scope: wantedScope, removed: 0, ambiguous: resolved.ambiguous };
  if (!resolved.updated) return { id: parsed.id, scope: wantedScope, removed: 0 };
  const targetScope = resolved.updated.scope;
  const dir = targetScope === "user" ? paths(cwd).user : paths(cwd).project;
  initializeDir(dir, targetScope);
  const file = join(dir, RECORDS);
  const filtered = purgeScopedRecordVersions(readFileSync(file, "utf8"), parsed.id, targetScope);
  if (filtered.uncertainLines.length) {
    throw new Error(`Cannot prove a complete purge for ${targetScope}:${parsed.id}: damaged JSONL may reference it on line${filtered.uncertainLines.length === 1 ? "" : "s"} ${filtered.uncertainLines.join(", ")}. Repair or remove those lines, then retry.`);
  }
  if (!filtered.removed) return { id: parsed.id, scope: targetScope, removed: 0 };
  atomicWriteFileSync(file, filtered.contents);
  invalidateRecordsCache(cwd);
  regenerateSummary(cwd, targetScope);
  regenerateProjectContext(cwd);
  const result: PurgeMemoryResult = { id: parsed.id, scope: targetScope, removed: filtered.removed };
  result.auditPath = writeMemoryPurgeAudit(cwd, result);
  updateProjectState(cwd, { lastPurgeAt: nowIso(), lastPurgedRecord: `${targetScope}:${parsed.id}`, lastPurgeRemoved: filtered.removed, lastPurgeAuditPath: result.auditPath });
  return result;
}
